//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    
    public partial class Student
    {
        public string StudentID { get; set; }
        public string StudentName { get; set; }
        public int DP { get; set; }
        public int ExamMark { get; set; }
        public int FinalMark { get; set; }

        public int calcFinal()
        {
            int final = 0;
            final = DP + ExamMark;
            return final;
        }
    }
}
