//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public string Address { get; set; }
        public decimal Cost { get; set; }
        public decimal Square_Meterage { get; set; }
        public string Description { get; set; }
        public System.DateTime Purchase_Date { get; set; }
        public string Use { get; set; }
    }
}
